# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Web\:
        resource: '../src/Web'
        exclude:
            - '../src/Web/DependencyInjection/'
            - '../src/Web/Entity/'
            - '../src/Web/Kernel.php'

    App\:
        resource: '../src/App'

    Domain\:
        resource: '../src/Domain'

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Doctrine/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Infrastructure\Doctrine\MemberEntityRepository:

    Infrastructure\Doctrine\SeniorityEntityRepository:

    Infrastructure\Doctrine\ToolEntityRepository:

    Domain\Member\Model\MembersRepository:
        alias: Infrastructure\Doctrine\MemberEntityRepository

    Domain\Tools\ToolRepository:
        alias: Infrastructure\Doctrine\ToolEntityRepository

    Domain\Seniority\SeniorityRepository:
        alias: Infrastructure\Doctrine\SeniorityEntityRepository