services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Domain\Member\Model\MembersRepository:
        alias: Tests\Behat\InMemoryMembersRepository